Fix swapping CVX token to USDC
AffineLabs/contracts pull request #330
Opened 2023-03-24 14:47 UTC by nodimdim

2023-03-27 17:14 UTC, larryob requested changes
Looking good, the ETH/USDC pool should be changed.

2023-03-27 17:14 UTC, larryob commented on src/strategies/ConvexStrategy.sol
> +                path: abi.encodePacked(address(CVX), fee, address(WETH), fee, address(asset)),
I'm pretty sure we want to be using the [0.05% pool](https://info.uniswap.org/#/pools/0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640) (500 fee).

2023-03-27 17:14 UTC, larryob commented on .gas-snapshot
> +L1DeltaNeutralTest:testClaimAndSellSushi() (gas: 1129960)
I don't think some of these gas costs should be changing. Can you run `foundryup`?

2023-03-27 17:14 UTC, larryob commented on src/test/ConvexStrategy.t.sol
>          deal(address(strategy.CVX()), address(strategy), 10e18);
Let's try to sell about $1k worth of both crv and cvx.

2023-03-31 13:46 UTC, nodimdim commented on src/test/ConvexStrategy.t.sol
> +        assertApproxEqRel(crvUsdc, 10.3e6, 0.1e18);
Turns out I was using the wrong price.

2023-05-02 14:09 UTC, merged