Re-Staking
AffineLabs/contracts pull request #388
Opened 2024-02-26 21:53 UTC by maruf0011

2024-02-26 22:17 UTC, tmoon requested changes

2024-02-26 22:17 UTC, tmoon commented on src/vaults/restaking/AffineReStaking.sol
> +    function sweep(address _token) external whenPaused onlyGovernance {
remove this--we can upgrade if necessary

2024-02-26 22:17 UTC, tmoon commented on src/vaults/restaking/AffineReStaking.sol
> +    function pause() external onlyGovernance {
add `pauseDeposit`

2024-02-26 22:17 UTC, tmoon commented on src/vaults/restaking/AffineReStaking.sol
> +import {AffineGovernable} from "src/utils/audited/AffineGovernable.sol";
maybe refactor the code into a private repo

2024-02-27 19:08 UTC, Omurshid commented on src/vaults/restaking/AffineReStaking.sol
> +
should prob unwrap the eth if token is weth and send it back as `value` since that's what they deposited

2024-02-27 19:09 UTC, Omurshid commented on src/vaults/restaking/AffineReStaking.sol
> +contract AffineReStaking is UUPSUpgradeable, AccessControlUpgradeable, PausableUpgradeable, AffineGovernable {
should we setup a function to migrate the assets to a new contract just in case?

2024-03-05 21:25 UTC, merged